# Generated by Django 3.0.2 on 2020-06-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200611_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
