# Generated by Django 3.0.2 on 2020-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200611_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
